name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true

      - run: flutter config --enable-windows-desktop

      - run: flutter build windows

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sketching
          path: build/windows/runner/Release
